# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imageUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 800)
        MainWindow.setStyleSheet("QMainWindow#MainWindow{\n"
"/*background-color: qconicalgradient(cx:0.525, cy:0.534, angle:180.1, stop:0 rgba(109, 177, 193, 255), stop:0.9801 rgba(255, 192, 192, 255));*/\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0.153, x2:1, y2:0.00595455, stop:0 rgba(109, 177, 193, 255), stop:0.721393 rgba(255, 192, 192, 255));\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-family: georgia;\n"
"font-size: 30pt;")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.title = QtWidgets.QLabel(self.widget_3)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout_4.addWidget(self.title)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.imageLabel = QtWidgets.QLabel(self.widget_2)
        self.imageLabel.setStyleSheet("image: url(:/newPrefix/bird.jpg);")
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")
        self.horizontalLayout_3.addWidget(self.imageLabel)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(300, 80))
        self.pushButton.setMaximumSize(QtCore.QSize(300, 80))
        self.pushButton.setStyleSheet("font-family: georgia;\n"
"font-size: 18pt;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.submitBtn = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.submitBtn.sizePolicy().hasHeightForWidth())
        self.submitBtn.setSizePolicy(sizePolicy)
        self.submitBtn.setMinimumSize(QtCore.QSize(300, 80))
        self.submitBtn.setMaximumSize(QtCore.QSize(300, 80))
        self.submitBtn.setStyleSheet("font-family: georgia;\n"
"font-size: 18pt;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.submitBtn.setObjectName("submitBtn")
        self.horizontalLayout.addWidget(self.submitBtn)
        self.verticalLayout_3.addWidget(self.widget)
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.outputTxt = QtWidgets.QLabel(self.widget_4)
        self.outputTxt.setMinimumSize(QtCore.QSize(500, 100))
        self.outputTxt.setStyleSheet("font-family: georgia;\n"
"font-size: 15pt;")
        self.outputTxt.setAlignment(QtCore.Qt.AlignCenter)
        self.outputTxt.setObjectName("outputTxt")
        self.horizontalLayout_2.addWidget(self.outputTxt)
        self.verticalLayout_3.addWidget(self.widget_4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Image Processing"))
        self.pushButton.setText(_translate("MainWindow", "Insert Image"))
        self.submitBtn.setText(_translate("MainWindow", "What is this image?"))
        self.outputTxt.setText(_translate("MainWindow", "Here will be the output text."))
import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
